before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: rxB4a7hqYjrdNuDzAg8/8o1w32NI8CQt8pNWkZTXQUm4iKQUhEhag+eAr0QwMydXULBDHcR56+QZR4SfvzSdYjNCuKyKO/Lq6tpe1QrU4rsVW6bNEaWWr3MvfifdOOOeD5dI5oQ/jaR5d3GeLRdg4H6O1vfoeQL0YoHRArrUZPtDKMDb9GBEN+YXefgnDSSay2uprLmhuZDfrKv/0/adFm11zEGrnuw0rfosCcDsX1mzpdBAq4zXBJVnUtFX3M/GcurvOF+ZgsPzfA4k4wrEcHmOHq4KT08Amb804IC1DRlWH3qP+9+qjIy5UrnYFs8fVXb9svP1GG3adbvgzs+1+u6vnCypMcWHk6Hry3VuN2sorGvn2V2LP8qN1DgLRfFf+iBmuKxRNRdFnd5e6YHAslolZGYe23+aAk04XJAHMKGov7z7okrcRnLJV8xAZ8N9UX/2N9SOk5TqINWNgiGmn0RxbB+kBZVEnnsKiOjsfevug7fK8rivDz4ifXVyQmUr4LbnhSTnkOQaPoizCluCJ/IAFUJwxcFtRTivVDpxxhfxrQyMZY6tj4r4LegibamkyK1HQzwlbGUmPW6ehtaJII/1mYCYMl+zeDa+S6X1ABS2X7amGZJhTDVwjkIh2Zfzz3x936nqoCxm/YsgyDLVl2ELx0kukNpNwdIxM1039KQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
